### ISSUE TITLE
Show the interval counter

### ISSUE THREAD

**Issue by motorollerscalatron** [pankona/mobu#25]
Apart from the total elapsed time, It might be useful if we can see how many intervals we have had in the session.

![image](https://user-images.githubusercontent.com/7314191/72117462-2c9d4400-3391-11ea-8598-1edebee7f674.png)

 - When we take a memo chronologically, it is easier to index the information in terms of intervals, instead of the elapsed time
   - (e.g. "we found the solution for the issue A in interval 3") 
 - The counter can be a clue to the even rotation of drivers (esp. when we assign some manually)

**Comment by kachick** [comment]
ref: https://github.com/pankona/mobu/discussions/50

**Comment by pankona** [comment]
Implemented!
